<?php
$_SERVER['API_GET'] = '';
$_SERVER['API_POST'] = '';
$_SERVER['DELAY_IN_S'] = 1;
$_SERVER['GITHUB_APP_NAME'] = '';
$_SERVER['GITHUB_CLIENT_ID'] = '';
$_SERVER['GITHUB_CLIENT_SECRET'] = '';
$_SERVER['GITLAB_APP_NAME'] = '';
$_SERVER['GITLAB_CLIENT_ID'] = '';
$_SERVER['GITLAB_CLIENT_SECRET'] = '';
$_SERVER['URL'] = '';